name: course
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=4.3.0
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.5
  - aws-c-mqtt=0.10.2
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - dataclasses-json=0.6.4
  - datasets=2.19.0
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - faiss-cpu=1.8.0
  - ffmpeg=4.3
  - filelock=3.13.4
  - fire=0.6.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - gnutls=3.6.13
  - greenlet=3.0.3
  - huggingface_hub=0.22.2
  - icu=73.2
  - idna=3.7
  - jinja2=3.1.3
  - joblib=1.4.0
  - jsonpatch=1.33
  - jsonpointer=2.4
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - langchain=0.1.16
  - langchain-community=0.0.34
  - langchain-core=0.1.46
  - langchain-text-splitters=0.0.1
  - langsmith=0.1.51
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libfaiss=1.8.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.17.0
  - libgoogle-cloud-storage=2.17.0
  - libgrpc=1.60.1
  - libhwloc=2.10.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.27
  - libparquet=15.0.0
  - libpng=1.6.43
  - libprotobuf=4.25.1
  - libre2-11=2023.09.01
  - libsentencepiece=0.1.99
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - marshmallow=3.21.1
  - mkl=2023.0.0
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - mypy_extensions=1.0.0
  - ncurses=6.4.20240210
  - nettle=3.6
  - networkx=3.3
  - nltk=3.8.1
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.2.1
  - orc=1.9.2
  - orjson=3.10.1
  - packaging=23.2
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - pthread-stubs=0.4
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pydantic=2.7.1
  - pydantic-core=2.18.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.12
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.4.16
  - requests=2.31.0
  - s2n=1.4.5
  - safetensors=0.4.3
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - sentence-transformers=2.7.0
  - sentencepiece=0.1.99
  - sentencepiece-python=0.1.99
  - sentencepiece-spm=0.1.99
  - setuptools=69.5.1
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sniffio=1.3.1
  - sqlalchemy=2.0.29
  - sympy=1.12
  - tbb=2021.12.0
  - tenacity=8.2.3
  - termcolor=2.4.0
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - tokenizers=0.19.1
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - tqdm=4.66.2
  - transformers=4.40.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_inspect=0.9.0
  - tzdata=2024a
  - ucx=1.15.0
  - urllib3=2.2.1
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - altair==5.3.0
      - blinker==1.8.1
      - cachetools==5.3.3
      - diskcache==5.6.3
      - fastapi==0.110.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - llama-cpp-python==0.2.65
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - protobuf==4.25.3
      - pydeck==0.9.0
      - pygments==2.17.2
      - rank-bm25==0.2.2
      - referencing==0.35.0
      - rich==13.7.1
      - rpds-py==0.18.0
      - smmap==5.0.1
      - starlette==0.37.2
      - streamlit==1.33.0
      - toml==0.10.2
      - toolz==0.12.1
      - tornado==6.4
      - uvicorn==0.29.0
      - watchdog==4.0.0
      - whisper==1.1.10
